### PR TITLE
AB#1351 - Explicitly validate pipeline access token

### PR DESCRIPTION
**Pull request by ndowmon**

### CODE REVIEW

**Review by aiwilliams — DISMISSED** [review]
@ndowmon Any reason to be concerned about the size of the set of resources returned by these endpoints? To put it another way, is there a way to limit the size to 1, in cases where the sets are large?

**Review by austinkelleher — APPROVED** [review]

**Comment by austinkelleher** [comment]
Can none of the steps in this integration run without the second access token being valid?

**Comment by ndowmon** [comment]
@austinkelleher no, only the pipeline step cannot be run without the second access token. However, as of now `clientPipelineAccessToken` is a required field in the integration definition. IMO it's best to keep it required and validate it. If customers in the future have reasons to not want to add pipeline access tokens, we can make it optional and only validate when it's there.

**Comment by ndowmon** [comment]
@aiwilliams good suggestion. I've added the `limit` query param to reduce the load on validation functions.

As an aside, it doesn't look like these APIs use pagination at all. I opened #13 to track adding pagination in the future, in case this becomes an issue.

**Review by aiwilliams — DISMISSED** [review]

**Review by aiwilliams — APPROVED** [review]

**Review by austinkelleher — APPROVED** [review]

**Pull request merged**
