### PR TITLE
Fix permissions properties

### PR DESCRIPTION
**Pull request by ndowmon**
The initial implementation of Artifactory created some mapped relationships which failed validation between `artifactory_permission` and `artifactory_user`/`artifactory_group`:

```
Error: Error uploading collected data (API response: code=RELATIONSHIP_UPLOAD_FAILED_VALIDATION, message="2 validation error(s):- Error in relationships[0]._mapping.targetEntity._rawData (reason=Expected string \| number \| boolean \| string[] \| number[] \| boolean[], but was object in _mapping.targetEntity._rawData)- Error in relationships[1]._mapping.targetEntity._rawData (reason=Expected string \| number \| boolean \| string[] \| number[] \| boolean[], but was object in _mapping.targetEntity._rawData)(code=RELATIONSHIP_UPLOAD_FAILED_VALIDATION, statusCode=400, correlationId=26b32336-a665-4b34-a22f-442e1a9bcb35)").
--
```

The object(s) in question were `buildPermissions` and `repositoryPermissions`:
```typescript
{
  ...
  buildPermissions: {
    read: true
  },
  repositoryPermissions: {
    read: true
  }
  ...
}
```

~~I've changed these to the following format in order to validate graph object requirements:~~
```typescript
{
  ...
  permissions: [
    'build:read',
    'repository:read',
  ],
  ...
}
```

I have **actually** changed to primitive type values: 
```typescript
{
  ...
  'permission:build:read': true,
  'permission:repository:read': true,
  ...
}
```

### CODE REVIEW

**Comment by ndowmon** [comment]
Psych! I didn't know this but apparently arrays are not allowed: 

```
(6:19:08 PM) - [job_abort] - Aborting integration job. (reason=Error uploading collected data (API response: code=RELATIONSHIP_UPLOAD_FAILED_VALIDATION, message="1 validation error(s): - Error in relationships[0].permissions (reason=ARRAYS_NOT_ALLOWED) (code=RELATIONSHIP_UPLOAD_FAILED_VALIDATION, statusCode=400, correlationId=a97fc218-b204-49b1-b97f-5b61f4375eff)").)
```

As an aside, it's a real pain to deploy anything with a linked package. Wondering if anyone has had any luck manually deploying linked packages.

**Comment by aiwilliams** [comment]
> apparently arrays are not allowed

Yah, not on relationships (edges) 😢 

> Wondering if anyone has had any luck manually deploying linked packages.

The reason linked packages don't work: Docker does not follow symlinks when transferring files to the context. Use `rsync` instead to put the build of your local package in place, something like:
```sh
rsync -rlpt --del --force --stats --exclude node_modules --exclude .git --exclude coverage --exclude .env* node_modules/@jupiterone/graph-azure/ deploy/node_modules/@jupiterone/graph-azure
```

**Comment by ndowmon** [comment]
Also opened https://github.com/JupiterOne/sdk/pull/336

**Comment by ndowmon** [comment]
Sent back to draft; found another issue with the types used in `createMappedRelationship` (which extends `Partial<Entity>`, which _does_ allow for non-primitive types.)

**Comment by ndowmon** [comment]
Manually deployed these fixes to dev and the integration job completed successfully:

Screen Shot 2020-09-14 at 4 22 06 PM

Also opened https://github.com/JupiterOne/sdk/pull/337

**Review by aiwilliams — APPROVED** [review]

**Pull request merged**
